/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lc_jni_NativeMethod */

#ifndef _Included_com_lc_jni_NativeMethod
#define _Included_com_lc_jni_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lc_jni_NativeMethod
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lc_jni_NativeMethod_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
